// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tempo;

namespace Tempo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190812130513_AddPaisIcone")]
    partial class AddPaisIcone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tempo.Models.Cidade", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condicao");

                    b.Property<string>("Icone");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Pais");

                    b.Property<decimal?>("Temperatura");

                    b.HasKey("Id");

                    b.ToTable("Cidade");
                });
#pragma warning restore 612, 618
        }
    }
}
